### ISSUE TITLE
Bug in MUX cd74hc4067

### ISSUE THREAD

**Issue by skolodi** [wokwi/wokwi-features#647]
Pleas correct the Component "board-cd74hc4067" its not works as expected. 
2 Issues found:
Only 1 part can be added or the simulator crashes.
And with one, no work as expected if you connect COM to an Arduino Pin instead Gnd to control it, doesn't work. 

Here fails with 1 part and only 1 measue with the Oficial HC4067.
https://wokwi.com/projects/376955374425446401

Here works with 4 parts and 64 measures, with a no oficial HC4067.
https://wokwi.com/projects/376936530062516225

regards!

**Comment by urish** [comment]
@Droog71 mind looking into this?

**Comment by skolodi** [comment]
Sorry...can't  see your comment complete. May be the picture or the link not attached?

**Comment by Droog71** [comment]
The issue was pin_init being used where pin_mode should have been used.
This has been fixed.
Here is an example with with multiple chips in the project and everything is working now.
https://wokwi.com/projects/378345758812972033

@skolodi 
@urish

**Comment by urish** [comment]
Thank you!

**Comment by skolodi** [comment]
Hi again. I still have problem with the MUX cd74hc4067 #647.
May be other bugs, but with 4 MUX, 
I need:
All the 4 MUX with the same S0, S1, S2, S3 ( const byte MUX_ADDR [4] = {A3, A2, A1, A0};)
All the 4 MUX with the same SIG (const byte MUX_OUTPUT (A8);)
Each MUX with diferent Enable. Mux 4 on pin 25, Mux3 on 24, Mux2 on 23, Mux 1 on 22 (const byte MUX_SELECT [4] = {25, 24, 23, 22};)
But don't take the correct measures.

See the project with the problem here: https://wokwi.com/projects/376946283692116993
If I simulate it on Simulide, it works, but on Wokwi don't. 

Thanks for your help and time.

**Comment by skolodi** [comment]
Hi again @urish. May be the change I made on the Example Project made by @Droog71 , shows the problem simplier and better. 
This works on real Arduino, works on Simulide, but I can't make it works fine on Wokwi.
All the 4 MUX with the same S0, S1, S2, S3 ( const byte MUX_ADDR [4] = {A3, A2, A1, A0};)
All the 4 MUX with the same SIG (const byte MUX_OUTPUT (A5);)
Each MUX with diferent Enable. Mux 4 on pin 5, Mux3 on 4, Mux2 on 3, Mux 1 on22 (const byte MUX_SELECT [4] = {5, 4, 3, 2};)
But don't take the correct measures of the potenciometers.

https://wokwi.com/projects/378946827241484289
Regards.

**Comment by Droog71** [comment]
> Hi again @urish. May be the change I made on the Example Project made by @Droog71 , shows the problem simplier and better. This works on real Arduino, works on Simulide, but I can't make it works fine on Wokwi. All the 4 MUX with the same S0, S1, S2, S3 ( const byte MUX_ADDR [4] = {A3, A2, A1, A0};) All the 4 MUX with the same SIG (const byte MUX_OUTPUT (A5);) Each MUX with diferent Enable. Mux 4 on pin 5, Mux3 on 4, Mux2 on 3, Mux 1 on22 (const byte MUX_SELECT [4] = {5, 4, 3, 2};) But don't take the correct measures of the potenciometers.
> 
> https://wokwi.com/projects/378946827241484289 Regards.

The problem is sharing the SIG pin.
I can make your project work by switching the SIG pin's mode to INPUT (floating) whenever the EN pin is high.
This will have to be done with a configurable attribute.
Otherwise, it will cause issues with other projects using a different configuration.

Ok, I have added the attribute. You should now be able to simulate your project.
You just have to add the attribute in diagram.json ie: `"attrs": { "floatingSig": "1" }`
Here is a demonstration @skolodi: https://wokwi.com/projects/383511417890576385
