### ISSUE TITLE
The My Projects personal page stopped generating and showing the miniatures

### ISSUE THREAD

**Issue by GabyGold67** [wokwi/wokwi-features#962]
**Describe the bug**
For some time the My Projects personal page was "sluggish" or took some time to generate the miniature depicting the project, now it seems completely stuck, not generating the miniatures ever, in my case for the last 3 days. @Koepel confirmed the problem.

**To Reproduce**
Generate a new project, save it, wait the miniature to be generated. I just tryed a simple one, justa an Arduino Nano and a led... it waited and failed.

**Expected behavior**
Have the miniature generated...

**Environment (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 133.0.6943.127 

**Additional context**
In the already simplistic **My Projects** page where the resources available to sort and find a project, in a ever growing collection  gets complicated, the miniatures gives a visual hint to find the  one we're looking for. And that's why I consider it needed.

Constructive comment: 
Having the two columns layout for the projects makes the readable section of the project name short, so  imporvising a folder tree to clasify them like I do (**environment/project/library/demoFileName**) becomes useless, there's no sorting capabilities and now there are no miniatures.

**Comment by urish** [comment]
Thanks for reporting! I've allocated more resources to the service that generates the thumbnails. Can you please check again now?

**Comment by GabyGold67** [comment]
Hi Uri,
   No, not generated... And if this adds some information at all, when I
open the project after a few seconds I see a pop-up message, photo
attached. Stranger as I'm already a paying subscriber to a Hobbyist+ plan...
Hope this helps.
Gaby.//

**Comment by urish** [comment]
Thanks for testing! 

Can't see the photo - you might need to go to the GitHub webpage to attach it properly.

**Comment by GabyGold67** [comment]
Sorry about that, I'll be sending it in a few minutes

**Comment by GabyGold67** [comment]
The offending message... :-)

![Image](https://github.com/user-attachments/assets/d1676cff-67c0-4c3d-9dd0-011feff4ac33)

**Comment by urish** [comment]
Thanks! Are you getting this for a specific project, or for multiple projects?
Can you share the link?

Also, which browser are you using?)

(I can't reproduce it here, and I also checked the build server logs, and the build servers for paid users are not under heavy load or anything).

**Comment by GabyGold67** [comment]
Hi Uri, 
   I just checked once again.
   The miniatures are back, the last project I was tweaking on was the last to appear, but now all missing miniatures are built and shown.

   About the message, it was appearing not while I tried to run a modified version that needed compilation. It was appearing randomly  on those last projects, after I entered into them, like if it was set asked to run as soon as I entered automatically. But I just entered them, I never asked the simulation to run, and they are not the most complex, but I was trying a simple new library for shift registers manipulation.

https://wokwi.com/projects/423063934421032961

   That's one of them.
   If you need some more information/testing please ask, I'm back on-line.

Gaby.//

**Comment by urish** [comment]
> It was appearing randomly on those last projects, after I entered into them, like if it was set asked to run as soon as I entered automatically.

Ok, thanks! Now I know what's happening. When you enter a project, Wokwi automatically tries to compile it, to make sure it's ready sooner if you want to run it. However, in that case, it's always using the standard build servers, not the premium ones. It should not display the warning if that fails. I'll fix that.

**Comment by GabyGold67** [comment]
Ah, OK, that makes sense, and it seems you could get the real problem out of the nonsense fluffy mishmash description I made.

Thank you!

Gaby.//

**Comment by urish** [comment]
Sure thing - and now, it should be fixed too (if you didn't request a build, you should not see an error). 

Please do let me know if this issue ever repeats!

**Comment by GabyGold67** [comment]
Hi @urish , I'm sorry, but the miniatures not being generated issue is back, at least for the projects added or modified in the last 20 hours.
Gaby.//
